def convert_watson_to_tag(watson):
    watsonstring = ""
    for obj in watson:
        watsonstring += obj

    if 'plastic' in watsonstring or 'water' in watsonstring or 'bottled' in watsonstring:
        return 'plastic'
    elif 'box' in watsonstring:
        return 'box'
    elif 'paper' in watsonstring or 'print' in watsonstring:
        return 'paper'
    elif 'can' in watsonstring or 'soda' in watsonstring or 'cola' in watsonstring:
        return 'can'
    elif 'glass' in watsonstring or 'beer' in watsonstring or 'bottle' in watsonstring:
        return 'glass'
    elif 'animal' in watsonstring or 'cat' in watsonstring or 'dog' in watsonstring:
        return 'animal'
    elif 'person' in watsonstring or 'adult' in watsonstring or 'people' in watsonstring:
        return 'person'
    else:
        return 'ndb'


def db_articles(watson):
    tag = convert_watson_to_tag(watson)
    articles = {'box':[("DIY Recycled Cardboard Vase","To make a beautiful recycled cardboard vase, you’ll need corrugated cardboard as well as a cardboard tube, an old CD, and a few other supplies. You cut the cardboard into small strips and then layer it around the tube. The CD serves as a base and helps the vase to stand up. When it’s finished, this is a lovely vase that you can paint or just leave plain.","http://madebylakshmi.com/2013/06/11/recycled-cardboard-vase/"),
                       ("Rolled Cardboard (Rice Sammy) Owl Ornament","This little owl is a hoot and so easy to make. You start by rolling cardboard for the body and when that’s finished you just do the same for the head and eyes. He’s such a little cutie and perfect for adding a little homemade décor to your home. You can add feathers – or make feathers from leaf shapes – and he’s all finished. Paint him if you want but I think the natural look is so much better.","https://www.pinterest.com/pin/212513676142615990"),
                       ("Repurposed Cardboard Guitar","If the little ones love making music, you can make them this adorable cardboard guitar that looks just like the real thing. These things also actually play music so they can strum their little hearts out. This is actually a great tool for little ones that want to learn how to play guitar.","http://www.makeit-loveit.com/2011/03/mister-make-it-and-love-it-series.html#more"),
                       ("Cardboard Cat Scratching Post","Cats love to scratch – those of us who own them know that all too well. If you have a cat, you really need a scratching post of some sort. Otherwise, they’ll scratch walls and furniture. So, why not take those empty cardboard boxes and make a scratching post to save your furnishings? You can make one out of corrugated cardboard and it will rival those that you see in pet shops for over $100. Your cat will love it and your furniture will love you.","http://maisonkuotidien.com/2013/07/19/catscraper-diy-cat-scratching-post/"),
                       ("DIY Cardboard Photo Frame","Cardboard photo frames are so easy to make and they’re perfect when you want something you can really customize. Not only are these great for decorating your own house, they make perfect gifts for others. And, since they’re made from recycled cardboard, they’re really cheap and they’re made in a fold design so they’re great for displaying pictures on the table or mantel.","http://www.ohohblog.com/2013/06/diy-cardboard-photo-frame.html"),
                       ("Recycled Cardboard Craft Storage","You’re crafty right? Then why not turn your cardboard box craft into something that will help you with all your craftiness? I love this recycled cardboard storage. It’s the perfect way to keep all of your craft supplies organized and it’s so very easy to make. You just cut around the boxes to give them a nice shelf look and then string them all together with twine. This is great for storing all sorts of things and won’t cost you anything but a little time.","https://paigebphotography.squarespace.com/home/2010/2/5/recycled-cardboard-storage.html"),
                       ("Make A Cardboard Paint Palette","Sometimes it's nice not to overthink it. Any craft project will be easier with this cardboard paint palette, complete with a handy thumb hole to keep things in balance.","https://www.bobvila.com/slideshow/17-creative-ways-to-reuse-cardboard-boxes-47420/diy-paint-palette"),
                       ("Decorative Recycled Cardboard Box","You would never believe that this beautiful decorative box was once a plain cardboard box. It’s so gorgeous and such a lovely thing to display. It’s also pretty easy to make and won’t take you long at all. This would be a great gift box or you can just use it to dress up the bedroom or bathroom. Just cover a box in burlap and then add “legs” and any other decorations that you want.","https://lookiewhatidid.blogspot.ca/2012/02/cardboard-box-transformation-with.html")],
                'plastic':[("Water Bottle Sprinkler","Sprinklers from Lowe’s are too expensive. Why not use that plastic water bottle from the back seat of your car? Buy a ¾ inch pipe, poke some holes in the water bottle, attach the hose. It’s a sprinkler! ","http://www.instructables.com/id/Soda-Bottle-Sprinkler/"),
                           ("Water Bottle Watering Can","Don’t you ever wish things in life were less expensive? Well they can be! Just cut holes in the top of your used water bottle cap, invert it, and you now have a watering can!","http://www.instructables.com/id/Soda-Bottle-Sprinkler/"),
                           ("Bird Feeder","Instead of chunking your water bottle in the trash after your workout, reuse it as a bird feeder! Simply poke holes in the sides of the water bottle, push pencils through the plastic, and fill it with bird seeds!","http://inhabitat.com/how-to-make-a-bird-feeder-from-recycled-materials/"),
                           ("Piggy Bottle Bank","Not only does this simple project recycle a plastic bottle and make an adorable piggy bank, it also encourages kids to starting saving and recycling from a young age. Just cut the bottle appropriately and then have fun creating these super cute designs that will look great on your shelves too. And it doesn’t necessarily have to be a pig; be creative and make all sorts of little animals!","http://www.allyou.com/budget-home/crafts/water-bottle-craft"),
                           ("DIY No-Sew Zipper Cases","Turn your old plastic bottles into useful and sturdy no-sew zipper cases that will help you organize your life, for almost no cost at all. You can use them to store all sorts of art and craft supplies. This is also an awesome back-to-school craft idea for kids. To make one, cut the plastic bottle, glue a zipper to it, customise the decorations and you’re done. You can learn how to make these creative zipper cases from plastic bottles here.","http://www.makeit-loveit.com/2015/01/no-sew-zipper-cases-from-old-soda-or-water-bottles.html")],
                'glass':[("Glass Beer Bottle Candles","Boutique candle stores can become way too expensive a lot of times. Instead of spending money on candles, spend it on beer (bottles)! After emptying the bottle either down the sink or in your stomach, simply heat the bottle, cut off the top, pour melted wax into the cylinder, and voila! Your own candle!","http://secretangrygerbil.blogspot.com/2012/12/how-to-make-beer-bottle-candles-first.html"),
                         ("Succulent Planters","It’s 2017 and succulents are all the rage. Why buy vases when you can make your own? Just cut the top off the bottle and smooth it out, its that simple. It takes 5 minutes to create and a lifetime to enjoy your newfound succulent garden. Now you can turn your glass tragedy into the ultimate conversation piece.","http://www.hgtv.com/design/decorating/design-101/10-ways-to-repurpose-glassware-pictures"),
                         ("Broken Glass Mosaic","Oh no! Did you drop the glass bottle again? Well don’t just throw the glass away; make a mosaic out of it! Grab some glue and maybe break some other colored glass bottles to create your own Mona Lisa.","http://www.instructables.com/id/Broken-Mirror-Mosaic/")],
                'can':[("Cookie Cutters","You just can never find the right cookie cutter in the right size and at the right time. Well, if you make your own, you can have exactly what you want when you need it. These DIY cookie cutters are super easy to make from any old soda can, and you can cut them into all of the shapes and sizes you need!","https://diyhshp.blogspot.com/2011/03/do-you-have-picky-eater.html"),
                       ("Soda Can Tab Small Pendant Light","This gorgeous lamp is made from the tabs of soda cans. It’s definitely unique and so gorgeous. Imagine having this hanging in the living room or even the bedroom. It’s flexible and very easy to make. You’ll need quite a few soda can tabs, so unless you drink tons of soda every week, you may want to have your friends and family help you to gather the tabs for this little project.","https://the3rsblog.wordpress.com/2011/10/17/soda-can-tab-small-pendant-light/"),
                       ("Soda Can Bracelets","These bracelets are really cute and very easy to make. Imagine giving these away as gifts. You’ll spend literally nothing since you’re recycling the materials from empty soda cans, and they certainly do make a unique fashion statement. You can dress them up however you want, so they’re perfectly customizable and imagine how many you can create from just one soda can!","https://twelvecraftstillchristmas.blogspot.com/2010/07/more-soda-can-jewelry-ugh.html"),
                       ("Soda Can Lanterns","These hanging lanterns are perfect for evenings on the porch. Imagine having them hanging outside during your summer parties! A tealight completes the look or you could even burn a citronella candle if you want during the warmer months. These are so easy to make, as are all the soda can projects, and add the perfect rustic touch to the porch or patio.","http://dollarstorecrafts.com/2012/02/make-soda-can-lanterns/"),
                       ("Candle Holders","A bit different than the lanterns are these amazing little tealight candle holders. You can use these indoors or out. Imagine them on your patio table or gracing the porch, or leave them on a foyer table – they’re unique and really creative. If you don’t want the actual can to show, you paint these as you would the lanterns or flowers and make them really match your décor.","https://aureliaslittleroom.com/upcycle-soda-cans/")],
                'paper':[("Origami","There are infinite ways to make cool shapes with your paper, and origami is the time tested way to go about crafting. It’s as simple as folding the paper and you are good to go!","http://www.origami-fun.com/"),
                         ("Newspaper Basket Weaving","",""),
                         ("Kitty Litter From Newspaper","That $100/year New York Times subscription is a tad bit expensive for just a bunch of words on a paper. Why not turn that into a one year’s supply of kitty litter too? Just soak the newspaper in dish soap, add some baking soda, and follow a few other steps to spread that $100 dollars out...onto the kitty litter basket.","https://www.treehugger.com/culture/pet-topic-make-your-own-newspaper-cat-litter.html"),
                         ("Paper Into Mulch","One man’s trash is another man’s treasure...or should I say another plant’s treasure. Throw some newspaper into a compost pile to create some nutritious soil for those plants. ","http://www.wikihow.com/Recycle-Paper"),
                         ("Make Paper Bags","Fabric is cheap. Leather is expensive. Information is priceless. Why buy bags made of leather when you can make your own out of information--or the newspaper that contains it! Read this guide to quickly create your own arsenal of newspaper bag attire.","http://www.instructables.com/id/5-minute-newspaper-bag/")],
                'person':[("No, humans are not recyclable!","Using humans in ways against their consent is highly unethical.", "http://www.memorialhermann.org/mental-health/locations/")],
                'animal': [("No, animals are not recyclable!",
                            "Animals are loving and caring beings that deserve love and attention, don't try to hurt them by recycling them.",
                            "https://www.google.com/search?q=pet+adoption+clinics+near+me&oq=pet+adoption+clin&aqs=chrome.2.0j69i57j0l4.7333j0j4&sourceid=chrome&ie=UTF-8")],
                'ndb':[("Wait......This item is not recyclable, but here's what you can do?","There are several ways to safely dispose of your item without creating hazardous waste. Click learn more to find places near you to dispose of your waste!","https://www.google.com/search?q=safe+disposal+and+recycling+centers+near+me&oq=safe+disposal+and+recycling+centers+near+me&gs_l=psy-ab.3...13317.17622.0.17819.14.14.0.0.0.0.106.1132.13j1.14.0....0...1.1.64.psy-ab..0.0.0....0.auazRfrcv8c")]}
    return articles[tag]

